version: "3.7"

services:
  spring-rabbitmq:   #Producer
    image: spring-rabbitmq:v100
    restart: unless-stopped
    build: .
    ports:
      - 9001:9001
    environment:
      spring.rabbitmq.addresses: rabbitmq
    links:
      - rabbitmq
    depends_on:
      - mongodb
  #spring-rabbitmq-consumer:   #Consumer
  #  image: spring-rabbitmq-consumer:v100
  #  restart: unless-stopped
  #  build: .
  #  ports:
  #    - 9002:9002
  #  environment:
  #    spring.rabbitmq.addresses: rabbitmq
  #    spring.data.mongodb.host: mongodb
      #mongodb.primary.host: mongodb
  #  links:
  #    - rabbitmq
  #  depends_on:
  #    - mongodb
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - 27017:27017
      #basicAuth credentials are "admin:pass", it is recommended you change this in your config.jsenvironment:
      #environment:
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      #- mongo-data:/data/db
      - ./Users/pablogonzalez/mongotmp/data/db:/data/db
volumes:
  mongo-data:
    driver: local