server:
  port: 9002
    #spring.rabbitmq.addresses = localhost:5672
spring:
  rabbitmq:
    addresses: rabbitmq:5672

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: GrandStoreDB
      database2: GrandStoreDB2
      db1:
        uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}
      db2:
        uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database2}

  datasource:
    url: jdbc:h2:mem:localGrandStoreDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect